# Schema for configuration files of the Image module.

image.effect.image_replace:
  type: mapping
  label: 'Image replace'
  mapping:
    image_style:
      type: string
      label: 'Image style'

field.field.*.*.*.third_party.image_replace:
  type: mapping
  label: 'Image replace field settings'
  mapping:
    image_style_map:
      type: sequence
      label: 'Image style mapping'
      sequence:
        type: mapping
        mapping:
          source_field:
            type: string
            label: 'Field to use when attempting to replace an image rendered with a given style.'
